version: '3.8' # Specify the Compose file format version
 
services:
  myapp: # Name of the service
     build: . # Use the current directory to build the image
     image: go-tutorial:latest # Tag the built image
     container_name: my-go-tutorial # Name the container